# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - develop
  - master
  - feature/pipeline

pool:
  vmImage: ubuntu-latest

variables:
  - name: version_image
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }} :
      value: 1.0-SNATSHOP
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/feature/pipeline') }} :
      value: latest
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/master') }} :
      value: 1.0-SNATSHOP
  - name: var_profile
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }} :
      value: dev
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/feature/pipeline') }} :
      value: prod
    ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/master') }} :
      value: dev

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'build'

  - task: Docker@2
    inputs:
      repository: 'jaider18/users-parking'
      containerRegistry: 'docker_auth'
      command: 'buildAndPush'
      Dockerfile: 'deployment/Dockerfile'
      buildContext: 'deployment'
      tags: '${{ variables.version_image }}'
      arguments: '--build-arg VAR_PROFILE=${{ variables.var_profile }}'