server:
  port: 8080
spring:
  application:
    name: "users"
  r2dbc:
    name: users
    username: root
    password: 12345678
    url: r2dbc:postgresql://parking.ciusywni3ifc.us-east-1.rds.amazonaws.com:5432/users?sslmode=require
    #pool:
      #initial-size: 12
      #max-size: 15
      #max-idle-time: 30
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "*"
app:
  description: Manejo de registro u otras operaciones con los usuarios del parqueadero
  version: 1.0